<?php
// Exam-style SQL in each exam dialect. Each test: the Access form (as the IEB
// memo writes it), the MySQL form and the Java DB form. 'check' runs after a
// changing statement (per dialect when dates differ).

$setup = [
  'access' => [
    "CREATE TABLE tblClients (ClientID INTEGER PRIMARY KEY, ClientName TEXT(40), Province TEXT(20), Loyalty INTEGER, Cell TEXT(12), Paid BIT)",
    "CREATE TABLE tblProducts (ProdID INTEGER PRIMARY KEY, ProdName TEXT(40), Fee INTEGER)",
    "CREATE TABLE tblSales (SaleID COUNTER PRIMARY KEY, ClientID INTEGER, ProdID INTEGER, License INTEGER, SaleDate DATETIME)",
  ],
  'mysql' => [
    "CREATE TABLE tblClients (ClientID INT PRIMARY KEY, ClientName VARCHAR(40), Province VARCHAR(20), Loyalty INT, Cell VARCHAR(12), Paid BOOLEAN)",
    "CREATE TABLE tblProducts (ProdID INT PRIMARY KEY, ProdName VARCHAR(40), Fee INT)",
    "CREATE TABLE tblSales (SaleID INT AUTO_INCREMENT PRIMARY KEY, ClientID INT, ProdID INT, License INT, SaleDate DATE)",
  ],
  'derby' => [
    "CREATE TABLE tblClients (ClientID INT PRIMARY KEY, ClientName VARCHAR(40), Province VARCHAR(20), Loyalty INT, Cell VARCHAR(12), Paid BOOLEAN)",
    "CREATE TABLE tblProducts (ProdID INT PRIMARY KEY, ProdName VARCHAR(40), Fee INT)",
    "CREATE TABLE tblSales (SaleID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY, ClientID INT, ProdID INT, License INT, SaleDate DATE)",
  ],
  'sqlite' => [
    "CREATE TABLE tblClients (ClientID INTEGER PRIMARY KEY, ClientName TEXT, Province TEXT, Loyalty INTEGER, Cell TEXT, Paid BOOLEAN)",
    "CREATE TABLE tblProducts (ProdID INTEGER PRIMARY KEY, ProdName TEXT, Fee INTEGER)",
    "CREATE TABLE tblSales (SaleID INTEGER PRIMARY KEY, ClientID INTEGER, ProdID INTEGER, License INTEGER, SaleDate DATE)",
  ],
];
$clients = [
  [1, 'Thandi Nkosi', 'Gauteng', 3, '0821234567', 1],
  [2, 'Pieter van Wyk', 'Western Cape', 3, '0837654321', 0],
  [3, 'Aisha Patel', 'KwaZulu-Natal', 2, '0719876543', 1],
  [4, 'Sipho Dlamini', 'Gauteng', 1, '0605551234', 0],
  [5, 'Megan Botha', 'Limpopo', 3, null, 1],
];
$products = [[1, 'Shield Deluxe', 450], [2, 'Shield Basic', 120], [3, 'Guard Premium', 600], [4, 'Guard Lite', 80], [5, 'Vault Deluxe', 350]];
$sales = [
  [1, 1, 1, 1234567, '2025-03-01'], [2, 2, 3, 2345678, '2024-11-15'], [3, 3, 1, 3456789, '2023-06-30'],
  [4, 1, 5, 4567890, '2026-01-10'], [5, 4, 2, 5678901, '2017-05-05'], [6, 2, 1, 6789012, '2026-08-20'],
];
foreach (['access', 'mysql', 'derby', 'sqlite'] as $d) {
  foreach ($clients as $c) {
    $cell = $c[4] === null ? 'NULL' : "'{$c[4]}'";
    $paid = $d === 'access' ? ($c[5] ? 'True' : 'False') : ($c[5] ? 'TRUE' : 'FALSE');
    if ($d === 'sqlite') $paid = $c[5];
    $setup[$d][] = "INSERT INTO tblClients VALUES ({$c[0]}, '{$c[1]}', '{$c[2]}', {$c[3]}, $cell, $paid)";
  }
  foreach ($products as $p) $setup[$d][] = "INSERT INTO tblProducts VALUES ({$p[0]}, '{$p[1]}', {$p[2]})";
  foreach ($sales as $s) {
    $date = $d === 'access' ? '#' . str_replace('-', '/', $s[4]) . '#' : "'{$s[4]}'";
    $setup[$d][] = "INSERT INTO tblSales (SaleID, ClientID, ProdID, License, SaleDate) VALUES ({$s[0]}, {$s[1]}, {$s[2]}, {$s[3]}, $date)";
  }
}

$tests = [
  ['id' => 't01', 'feature' => 'Text in double quotes',
   'access' => "SELECT ClientName FROM tblClients WHERE Loyalty = 3 AND Province <> \"Gauteng\" ORDER BY ClientName",
   'mysql'  => "SELECT ClientName FROM tblClients WHERE Loyalty = 3 AND Province <> \"Gauteng\" ORDER BY ClientName",
   'derby'  => "SELECT ClientName FROM tblClients WHERE Loyalty = 3 AND Province <> 'Gauteng' ORDER BY ClientName"],
  ['id' => 't02', 'feature' => 'LIKE with * (Access) / % wildcard',
   'access' => "SELECT ProdName FROM tblProducts WHERE ProdName LIKE '*Deluxe' ORDER BY ProdName",
   'mysql'  => "SELECT ProdName FROM tblProducts WHERE ProdName LIKE '%Deluxe' ORDER BY ProdName",
   'derby'  => "SELECT ProdName FROM tblProducts WHERE ProdName LIKE '%Deluxe' ORDER BY ProdName"],
  ['id' => 't02b', 'feature' => 'LIKE with % in Access',
   'access' => "SELECT ProdName FROM tblProducts WHERE ProdName LIKE '%Deluxe' ORDER BY ProdName"],
  ['id' => 't03', 'feature' => 'COUNT(*) AS alias',
   'access' => "SELECT COUNT(*) AS NumSales FROM tblSales",
   'mysql'  => "SELECT COUNT(*) AS NumSales FROM tblSales",
   'derby'  => "SELECT COUNT(*) AS NumSales FROM tblSales"],
  ['id' => 't04', 'feature' => 'YEAR(NOW()) - YEAR(date)',
   'access' => "SELECT SaleID FROM tblSales WHERE YEAR(NOW()) - YEAR(SaleDate) <= 1 ORDER BY SaleID",
   'mysql'  => "SELECT SaleID FROM tblSales WHERE YEAR(NOW()) - YEAR(SaleDate) <= 1 ORDER BY SaleID",
   'derby'  => "SELECT SaleID FROM tblSales WHERE YEAR(CURRENT_DATE) - YEAR(SaleDate) <= 1 ORDER BY SaleID"],
  ['id' => 't05', 'feature' => 'Join in WHERE',
   'access' => "SELECT ClientName, License FROM tblSales, tblClients WHERE tblSales.ClientID = tblClients.ClientID ORDER BY License",
   'mysql'  => "SELECT ClientName, License FROM tblSales, tblClients WHERE tblSales.ClientID = tblClients.ClientID ORDER BY License",
   'derby'  => "SELECT ClientName, License FROM tblSales, tblClients WHERE tblSales.ClientID = tblClients.ClientID ORDER BY License"],
  ['id' => 't06', 'feature' => '3-table INNER JOIN with Access brackets + GROUP BY/HAVING',
   'access' => "SELECT Province, SUM(Fee) AS ValueOfSales FROM tblProducts INNER JOIN (tblClients INNER JOIN tblSales ON tblSales.ClientID = tblClients.ClientID) ON tblProducts.ProdID = tblSales.ProdID GROUP BY Province HAVING SUM(Fee) > 500 ORDER BY Province",
   'mysql'  => "SELECT Province, SUM(Fee) AS ValueOfSales FROM tblProducts INNER JOIN (tblClients INNER JOIN tblSales ON tblSales.ClientID = tblClients.ClientID) ON tblProducts.ProdID = tblSales.ProdID GROUP BY Province HAVING SUM(Fee) > 500 ORDER BY Province",
   'derby'  => "SELECT Province, SUM(Fee) AS ValueOfSales FROM tblProducts INNER JOIN (tblClients INNER JOIN tblSales ON tblSales.ClientID = tblClients.ClientID) ON tblProducts.ProdID = tblSales.ProdID GROUP BY Province HAVING SUM(Fee) > 500 ORDER BY Province"],
  ['id' => 't06b', 'feature' => '3-table INNER JOIN without brackets',
   'access' => "SELECT Province, SUM(Fee) AS ValueOfSales FROM tblSales INNER JOIN tblClients ON tblSales.ClientID = tblClients.ClientID INNER JOIN tblProducts ON tblProducts.ProdID = tblSales.ProdID GROUP BY Province ORDER BY Province",
   'mysql'  => "SELECT Province, SUM(Fee) AS ValueOfSales FROM tblSales INNER JOIN tblClients ON tblSales.ClientID = tblClients.ClientID INNER JOIN tblProducts ON tblProducts.ProdID = tblSales.ProdID GROUP BY Province ORDER BY Province",
   'derby'  => "SELECT Province, SUM(Fee) AS ValueOfSales FROM tblSales INNER JOIN tblClients ON tblSales.ClientID = tblClients.ClientID INNER JOIN tblProducts ON tblProducts.ProdID = tblSales.ProdID GROUP BY Province ORDER BY Province"],
  ['id' => 't07', 'feature' => 'Subquery against AVG',
   'access' => "SELECT ProdName FROM tblProducts WHERE Fee > (SELECT AVG(Fee) FROM tblProducts) ORDER BY ProdName",
   'mysql'  => "SELECT ProdName FROM tblProducts WHERE Fee > (SELECT AVG(Fee) FROM tblProducts) ORDER BY ProdName",
   'derby'  => "SELECT ProdName FROM tblProducts WHERE Fee > (SELECT AVG(Fee) FROM tblProducts) ORDER BY ProdName"],
  ['id' => 't08', 'feature' => 'UPDATE rebuilding text (LEFT, LEN, &)',
   'access' => "UPDATE tblProducts SET ProdName = LEFT(ProdName, LEN(ProdName) - 7) & ' Premium' WHERE ProdName LIKE '*Deluxe'",
   'mysql'  => "UPDATE tblProducts SET ProdName = CONCAT(LEFT(ProdName, LENGTH(ProdName) - 7), ' Premium') WHERE ProdName LIKE '%Deluxe'",
   'derby'  => "UPDATE tblProducts SET ProdName = SUBSTR(ProdName, 1, LENGTH(ProdName) - 7) || ' Premium' WHERE ProdName LIKE '%Deluxe'",
   'check'  => "SELECT ProdName FROM tblProducts ORDER BY ProdID"],
  ['id' => 't09', 'feature' => 'INSERT with random number and date literal',
   'access' => "INSERT INTO tblSales (ClientID, ProdID, License, SaleDate) VALUES (5, 4, INT(RND()*1000001+1000000), #2025/03/25#)",
   'mysql'  => "INSERT INTO tblSales (ClientID, ProdID, License, SaleDate) VALUES (5, 4, FLOOR(RAND()*1000001+1000000), '2025-03-25')",
   'derby'  => "INSERT INTO tblSales (ClientID, ProdID, License, SaleDate) VALUES (5, 4, CAST(RANDOM()*1000001+1000000 AS INT), '2025-03-25')",
   'check'  => "SELECT ClientID, ProdID FROM tblSales WHERE ClientID = 5 AND License >= 1000000 AND License <= 2000001",
   'checkDate' => ['access' => "SELECT COUNT(*) FROM tblSales WHERE SaleDate = #2025/03/25#", 'other' => "SELECT COUNT(*) FROM tblSales WHERE SaleDate = '2025-03-25'"]],
  ['id' => 't10', 'feature' => 'Top 3',
   'access' => "SELECT TOP 3 ProdName, Fee FROM tblProducts ORDER BY Fee DESC",
   'mysql'  => "SELECT ProdName, Fee FROM tblProducts ORDER BY Fee DESC LIMIT 3",
   'derby'  => "SELECT ProdName, Fee FROM tblProducts ORDER BY Fee DESC FETCH FIRST 3 ROWS ONLY"],
  ['id' => 't11', 'feature' => 'MID, RIGHT, UCASE, concatenating a number',
   'access' => "SELECT MID(Cell, 4, 3) AS Middle, RIGHT(ClientName, 4) AS Last4, UCASE(LEFT(Province, 3)) & '-' & Loyalty AS Code FROM tblClients ORDER BY ClientID",
   'mysql'  => "SELECT MID(Cell, 4, 3) AS Middle, RIGHT(ClientName, 4) AS Last4, CONCAT(UCASE(LEFT(Province, 3)), '-', Loyalty) AS Code FROM tblClients ORDER BY ClientID",
   'derby'  => "SELECT SUBSTR(Cell, 4, 3) AS Middle, SUBSTR(ClientName, LENGTH(ClientName) - 3) AS Last4, UPPER(SUBSTR(Province, 1, 3)) || '-' || TRIM(CHAR(Loyalty)) AS Code FROM tblClients ORDER BY ClientID"],
  ['id' => 't12', 'feature' => 'ROUND a calculated field',
   'access' => "SELECT ProdName, ROUND(Fee * 1.15, 2) AS WithVAT FROM tblProducts ORDER BY ProdID",
   'mysql'  => "SELECT ProdName, ROUND(Fee * 1.15, 2) AS WithVAT FROM tblProducts ORDER BY ProdID",
   'derby'  => "SELECT ProdName, ROUND(Fee * 1.15, 2) AS WithVAT FROM tblProducts ORDER BY ProdID"],
  ['id' => 't13', 'feature' => 'Unmatched rows: NOT IN',
   'access' => "SELECT ProdName FROM tblProducts WHERE ProdID NOT IN (SELECT ProdID FROM tblSales)",
   'mysql'  => "SELECT ProdName FROM tblProducts WHERE ProdID NOT IN (SELECT ProdID FROM tblSales)",
   'derby'  => "SELECT ProdName FROM tblProducts WHERE ProdID NOT IN (SELECT ProdID FROM tblSales)"],
  ['id' => 't14', 'feature' => 'Unmatched rows: LEFT JOIN ... IS NULL',
   'access' => "SELECT ClientName FROM tblClients LEFT JOIN tblSales ON tblClients.ClientID = tblSales.ClientID WHERE tblSales.SaleID IS NULL",
   'mysql'  => "SELECT ClientName FROM tblClients LEFT JOIN tblSales ON tblClients.ClientID = tblSales.ClientID WHERE tblSales.SaleID IS NULL",
   'derby'  => "SELECT ClientName FROM tblClients LEFT JOIN tblSales ON tblClients.ClientID = tblSales.ClientID WHERE tblSales.SaleID IS NULL"],
  ['id' => 't15', 'feature' => 'INSERT ... SELECT with a date constant',
   'access' => "INSERT INTO tblSales (ClientID, ProdID, License, SaleDate) SELECT ClientID, 4, 9999999, #2026/09/01# FROM tblClients WHERE Province = 'Gauteng'",
   'mysql'  => "INSERT INTO tblSales (ClientID, ProdID, License, SaleDate) SELECT ClientID, 4, 9999999, '2026-09-01' FROM tblClients WHERE Province = 'Gauteng'",
   'derby'  => "INSERT INTO tblSales (ClientID, ProdID, License, SaleDate) SELECT ClientID, 4, 9999999, DATE('2026-09-01') FROM tblClients WHERE Province = 'Gauteng'",
   'check'  => "SELECT ClientID FROM tblSales WHERE ProdID = 4 ORDER BY ClientID"],
  ['id' => 't16', 'feature' => 'DELETE by date',
   'access' => "DELETE FROM tblSales WHERE SaleDate < #2018/01/01#",
   'mysql'  => "DELETE FROM tblSales WHERE SaleDate < '2018-01-01'",
   'derby'  => "DELETE FROM tblSales WHERE SaleDate < '2018-01-01'",
   'check'  => "SELECT SaleID FROM tblSales ORDER BY SaleID"],
  ['id' => 't17', 'feature' => 'DISTINCT, BETWEEN, IN',
   'access' => "SELECT DISTINCT Province FROM tblClients WHERE Loyalty BETWEEN 2 AND 3 AND Province IN ('Gauteng', 'Limpopo', 'Western Cape') ORDER BY Province",
   'mysql'  => "SELECT DISTINCT Province FROM tblClients WHERE Loyalty BETWEEN 2 AND 3 AND Province IN ('Gauteng', 'Limpopo', 'Western Cape') ORDER BY Province",
   'derby'  => "SELECT DISTINCT Province FROM tblClients WHERE Loyalty BETWEEN 2 AND 3 AND Province IN ('Gauteng', 'Limpopo', 'Western Cape') ORDER BY Province"],
  ['id' => 't18', 'feature' => 'Whole number / whole number',
   'access' => "SELECT Fee / 100 AS Hundreds FROM tblProducts WHERE ProdID = 2",
   'mysql'  => "SELECT Fee / 100 AS Hundreds FROM tblProducts WHERE ProdID = 2",
   'derby'  => "SELECT Fee / 100 AS Hundreds FROM tblProducts WHERE ProdID = 2"],
  ['id' => 't19', 'feature' => "= with different capitals ('gauteng')",
   'access' => "SELECT ClientName FROM tblClients WHERE Province = 'gauteng' ORDER BY ClientName",
   'mysql'  => "SELECT ClientName FROM tblClients WHERE Province = 'gauteng' ORDER BY ClientName",
   'derby'  => "SELECT ClientName FROM tblClients WHERE Province = 'gauteng' ORDER BY ClientName"],
  ['id' => 't20', 'feature' => 'LIKE with different capitals',
   'access' => "SELECT ClientName FROM tblClients WHERE ClientName LIKE '*nkosi*'",
   'mysql'  => "SELECT ClientName FROM tblClients WHERE ClientName LIKE '%nkosi%'",
   'derby'  => "SELECT ClientName FROM tblClients WHERE ClientName LIKE '%nkosi%'"],
  ['id' => 't21', 'feature' => 'Days between two dates',
   'access' => "SELECT SaleID, #2026/09/25# - SaleDate AS Days FROM tblSales WHERE SaleID = 1",
   'mysql'  => "SELECT SaleID, DATEDIFF('2026-09-25', SaleDate) AS Days FROM tblSales WHERE SaleID = 1",
   'derby'  => "SELECT SaleID, {fn TIMESTAMPDIFF(SQL_TSI_DAY, SaleDate, DATE('2026-09-25'))} AS Days FROM tblSales WHERE SaleID = 1"],
  ['id' => 't22', 'feature' => 'MONTH() and DAY()',
   'access' => "SELECT SaleID FROM tblSales WHERE MONTH(SaleDate) = 3 AND DAY(SaleDate) = 1",
   'mysql'  => "SELECT SaleID FROM tblSales WHERE MONTH(SaleDate) = 3 AND DAY(SaleDate) = 1",
   'derby'  => "SELECT SaleID FROM tblSales WHERE MONTH(SaleDate) = 3 AND DAY(SaleDate) = 1"],
  ['id' => 't23', 'feature' => 'GROUP BY missing a selected field (exam: error)',
   'access' => "SELECT Province, ClientName, COUNT(*) AS Num FROM tblClients GROUP BY Province",
   'mysql'  => "SELECT Province, ClientName, COUNT(*) AS Num FROM tblClients GROUP BY Province",
   'derby'  => "SELECT Province, ClientName, COUNT(*) AS Num FROM tblClients GROUP BY Province"],
  ['id' => 't24', 'feature' => 'Alias used in HAVING',
   'access' => "SELECT Province, COUNT(*) AS Num FROM tblClients GROUP BY Province HAVING Num > 1",
   'mysql'  => "SELECT Province, COUNT(*) AS Num FROM tblClients GROUP BY Province HAVING Num > 1",
   'derby'  => "SELECT Province, COUNT(*) AS Num FROM tblClients GROUP BY Province HAVING Num > 1"],
  ['id' => 't25', 'feature' => 'Yes/No field = True',
   'access' => "SELECT ClientName FROM tblClients WHERE Paid = True ORDER BY ClientName",
   'mysql'  => "SELECT ClientName FROM tblClients WHERE Paid = TRUE ORDER BY ClientName",
   'derby'  => "SELECT ClientName FROM tblClients WHERE Paid = TRUE ORDER BY ClientName"],
  ['id' => 't26', 'feature' => 'IIF / CASE',
   'access' => "SELECT ClientName, IIF(Loyalty = 3, 'Gold', 'Other') AS Grade FROM tblClients ORDER BY ClientID",
   'mysql'  => "SELECT ClientName, IF(Loyalty = 3, 'Gold', 'Other') AS Grade FROM tblClients ORDER BY ClientID",
   'derby'  => "SELECT ClientName, CASE WHEN Loyalty = 3 THEN 'Gold' ELSE 'Other' END AS Grade FROM tblClients ORDER BY ClientID"],
  ['id' => 't08b', 'feature' => 'UPDATE with % in Access',
   'access' => "UPDATE tblProducts SET ProdName = LEFT(ProdName, LEN(ProdName) - 7) & ' Premium' WHERE ProdName LIKE '%Deluxe'",
   'check'  => "SELECT ProdName FROM tblProducts ORDER BY ProdID"],
  ['id' => 't20b', 'feature' => 'LIKE % with different capitals (Access)',
   'access' => "SELECT ClientName FROM tblClients WHERE ClientName LIKE '%nkosi%'"],
  ['id' => 't35', 'feature' => '& to join text',
   'access' => "SELECT ClientName & ' (' & Province & ')' AS Label FROM tblClients WHERE ClientID = 1",
   'mysql'  => "SELECT CONCAT(ClientName, ' (', Province, ')') AS Label FROM tblClients WHERE ClientID = 1",
   'derby'  => "SELECT ClientName || ' (' || Province || ')' AS Label FROM tblClients WHERE ClientID = 1"],
  ['id' => 't36', 'feature' => 'INT((date - date) / 365) (CAPS 25N)',
   'access' => "SELECT INT((#2026/09/25# - SaleDate) / 365) AS Yrs FROM tblSales WHERE SaleID = 5",
   'mysql'  => "SELECT FLOOR(DATEDIFF('2026-09-25', SaleDate) / 365) AS Yrs FROM tblSales WHERE SaleID = 5",
   'derby'  => "SELECT {fn TIMESTAMPDIFF(SQL_TSI_DAY, SaleDate, DATE('2026-09-25'))} / 365 AS Yrs FROM tblSales WHERE SaleID = 5"],
  ['id' => 't27', 'feature' => 'FORMAT a date',
   'access' => "SELECT FORMAT(SaleDate, 'dd/mm/yyyy') AS Nice FROM tblSales WHERE SaleID = 1",
   'mysql'  => "SELECT DATE_FORMAT(SaleDate, '%d/%m/%Y') AS Nice FROM tblSales WHERE SaleID = 1",
   'derby'  => "SELECT SUBSTR(CHAR(SaleDate), 9, 2) || '/' || SUBSTR(CHAR(SaleDate), 6, 2) || '/' || SUBSTR(CHAR(SaleDate), 1, 4) AS Nice FROM tblSales WHERE SaleID = 1"],
  ['id' => 't28', 'feature' => 'Date literal in WHERE',
   'access' => "SELECT SaleID FROM tblSales WHERE SaleDate >= #2025/01/01# ORDER BY SaleID",
   'mysql'  => "SELECT SaleID FROM tblSales WHERE SaleDate >= '2025-01-01' ORDER BY SaleID",
   'derby'  => "SELECT SaleID FROM tblSales WHERE SaleDate >= '2025-01-01' ORDER BY SaleID"],
  ['id' => 't29', 'feature' => 'Text + text with + (Access alternative)',
   'access' => "SELECT ClientName + ' (' + Province + ')' AS Label FROM tblClients WHERE ClientID = 1"],
  ['id' => 't30', 'feature' => 'LEN / LENGTH',
   'access' => "SELECT ClientName FROM tblClients WHERE LEN(ClientName) > 12 ORDER BY ClientName",
   'mysql'  => "SELECT ClientName FROM tblClients WHERE LENGTH(ClientName) > 12 ORDER BY ClientName",
   'derby'  => "SELECT ClientName FROM tblClients WHERE LENGTH(ClientName) > 12 ORDER BY ClientName"],
  ['id' => 't31', 'feature' => 'FORMAT as currency (CAPS 9/15)',
   'access' => "SELECT FORMAT(Fee, \"Currency\") AS Price FROM tblProducts WHERE ProdID = 1",
   'mysql'  => "SELECT CONCAT('R', FORMAT(Fee, 2)) AS Price FROM tblProducts WHERE ProdID = 1",
   'derby'  => "SELECT 'R' || TRIM(CHAR(CAST(Fee AS DECIMAL(10,2)))) AS Price FROM tblProducts WHERE ProdID = 1"],
  ['id' => 't32', 'feature' => 'DELETE * FROM (Access form)',
   'access' => "DELETE * FROM tblSales WHERE ClientID = 4",
   'check'  => "SELECT COUNT(*) FROM tblSales"],
  ['id' => 't33', 'feature' => 'Alias with a space',
   'access' => "SELECT SUM(Fee) AS [Total Amount] FROM tblProducts",
   'mysql'  => "SELECT SUM(Fee) AS `Total Amount` FROM tblProducts",
   'derby'  => "SELECT SUM(Fee) AS \"Total Amount\" FROM tblProducts"],
  ['id' => 't34', 'feature' => 'User input glued in with double quotes (CAPS house style)',
   'access' => "SELECT ClientName FROM tblClients WHERE Province = \"Gauteng\" AND ClientName LIKE \"%Nkosi%\""],
];

if (PHP_SAPI === 'cli' && realpath($argv[0]) === __FILE__) {
  file_put_contents(__DIR__ . '/tests.json', json_encode(['setup' => $setup, 'tests' => $tests], JSON_PRETTY_PRINT));
  // A flat, tab-separated copy for RunJdbc.java (no JSON library in Java).
  $flat = [];
  foreach ($setup as $d => $list) foreach ($list as $s) $flat[] = "setup\t$d\t$s";
  foreach ($tests as $t) {
    foreach (['access', 'mysql', 'derby'] as $d) if (!empty($t[$d])) $flat[] = "test\t{$t['id']}\t$d\tmain\t{$t[$d]}";
    if (!empty($t['check'])) $flat[] = "test\t{$t['id']}\t*\tcheck\t{$t['check']}";
    if (!empty($t['checkDate'])) {
      $flat[] = "test\t{$t['id']}\taccess\tcheckDate\t{$t['checkDate']['access']}";
      $flat[] = "test\t{$t['id']}\tother\tcheckDate\t{$t['checkDate']['other']}";
    }
  }
  file_put_contents(__DIR__ . '/tests-flat.tsv', implode("\n", $flat) . "\n");
  echo count($tests), " tests written\n";
}
